// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjhwldzebshberdwuwlf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqaHdsZHplYnNoYmVyZHd1d2xmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMDA5NzEsImV4cCI6MjA1ODc3Njk3MX0.Hnk9Eug4czSw6seYs45cLmd_qpg5FplXsdcpEOCLgQU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);